# Generated by Django 5.2.6 on 2025-09-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
